stages:
  - lint
  - build-image

lint:
  image: node:8.12.0-alpine
  stage: lint
  script:
    - npm install
    - ./node_modules/.bin/eslint ./app.js
    - ./node_modules/.bin/eslint ./routes/*


build-image:
  image: tmaier/docker-compose:17.09
  stage: build-image
  services:
    - docker:dind
  script:
    - docker-compose build
